name: Release Cross-Platform Executables
on:
  push:

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        rid: [win-x64, linux-x64, osx-x64]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: npm install
        working-directory: Library
        run: npm install
      - name: Tailwind build
        working-directory: Library
        run: npm run tailwind-build
      - name: dotnet restore
        run: dotnet restore Server/Server.csproj
      - name: dotnet publish
        run: dotnet publish Server/Server.csproj -c Release -r ${{ matrix.rid }} --self-contained true -o ./publish/${{ matrix.rid }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.rid }}
          path: ./publish/${{ matrix.rid }}
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./publish/${{ matrix.rid }}/*
          tag: ${{ github.ref }}
